### ISSUE TITLE
Remove share and send fragments & associated layouts

### ISSUE THREAD

**Issue by pavitrawalia** [pavitrawalia/Calcify#10]

**Comment by parjanyaacoder** [comment]
I would like to work on this issue.Can I?

**Comment by pavitrawalia** [comment]
@parjanyaacoder go ahead

**Comment by parjanyaacoder** [comment]
Do I have to delete send and share folder under java/calcify/ui also??

**Comment by pavitrawalia** [comment]
@parjanyaacoder yes you have to delete all files associated with send and share fragments

**Comment by pavitrawalia** [comment]
issue fixed (Jan 5 6:51 PM)
