### ISSUE TITLE
Create functionality of Unit Conversion

### ISSUE THREAD

**Issue by pavitrawalia** [pavitrawalia/Calcify#12]

**Comment by MahmoudMabrok** [comment]
could i work on it at Coding peroid

**Comment by pavitrawalia** [comment]
@MahmoudMabrok You can work on it after the coding period starts.

**Comment by pavitrawalia** [comment]
@MahmoudMabrok Go ahead

**Comment by MahmoudMabrok** [comment]
could you provide list of functionality you need in app so i implement it

**Comment by pavitrawalia** [comment]
@MahmoudMabrok We need to have two dropdown menu elements containing various kind of units like for kilometre,metre, litre, etc
we must a have a swap button in between that will swap the units.
the UI will appear like we have in google translate

**Comment by pavitrawalia** [comment]
in case you are facing any issue, you can ping me personally in discord server

**Comment by pavitrawalia** [comment]
@MahmoudMabrok updates?

**Comment by MahmoudMabrok** [comment]
recent days there are problems, busy tiems. 
I will start.

**Comment by MahmoudMabrok** [comment]
I will work for logic(is UI present?)

**Comment by pavitrawalia** [comment]
@MahmoudMabrok UI is not present. Would you like to create it or i will create a seperate issue for the UI

**Comment by MahmoudMabrok** [comment]
#7  it exists so  i would like to do it then do current issue (i.e un-assigne me from current, assign to ui task) @pavitrawalia

**Comment by pavitrawalia** [comment]
@MahmoudMabrok you can comment on that issue so that i can assign it to you

**Comment by utpalendubarman** [comment]
I want to work

**Comment by MahmoudMabrok** [comment]
I have finished UI #24 , could i start doing its  functionality

**Comment by pavitrawalia** [comment]
@MahmoudMabrok go ahead

**Comment by MahmoudMabrok** [comment]
ok thanks @pavitrawalia
