### ISSUE TITLE
add two more categories in the navigation drawer

### ISSUE THREAD

**Issue by pavitrawalia** [pavitrawalia/Calcify#39]
Category 1: About /Info
Category 2: Contact us

**Comment by parjanyaacoder** [comment]
I would like to work on this issue

**Comment by pavitrawalia** [comment]
@parjanyaacoder go ahead

**Comment by pavitrawalia** [comment]
@parjanyaacoder updates?

**Comment by thesrijande** [comment]
I want to contribute on this issue, please assign me

**Comment by pavitrawalia** [comment]
@thesrijande go ahead

**Comment by pavitrawalia** [comment]
issue resolved
