### ISSUE TITLE
Design a logo for the app

### ISSUE THREAD

**Issue by pavitrawalia** [pavitrawalia/Calcify#4]

**Comment by SubhradeepSS** [comment]
@pavitrawalia I would like to work on this

**Comment by pavitrawalia** [comment]
@SubhradeepSS  I have assigned you the issue .You can create a PR after the coding period starts.

**Comment by pavitrawalia** [comment]
@SubhradeepSS You can now start working on the issue.

**Comment by pavitrawalia** [comment]
@SubhradeepSS  Go ahead

**Comment by pavitrawalia** [comment]
@SubhradeepSS updates?

**Comment by SubhradeepSS** [comment]
> 
> 
> @SubhradeepSS updates?

I am working on a different project.U can assign it to others

**Comment by utpalendubarman** [comment]
I want to contribute

**Comment by pavitrawalia** [comment]
@utpalendubarman go ahead

**Comment by pavitrawalia** [comment]
issue resolved
