### ISSUE TITLE
Improve UI in GPA Calculator activity

### ISSUE THREAD

**Issue by pavitrawalia** [pavitrawalia/Calcify#40]
UI isn't responsive 
Description: credit  and grade score overlaps each other in the header

**Comment by agarwalBinay18** [comment]
i want to work on this issue

**Comment by pavitrawalia** [comment]
@agarwalBinay18 go ahead

**Comment by pavitrawalia** [comment]
@agarwalBinay18 updates?

**Comment by thesrijande** [comment]
assign me

**Comment by pavitrawalia** [comment]
@thesrijande go ahead
