### ISSUE TITLE
Create a splash screen 

### ISSUE THREAD

**Issue by pavitrawalia** [pavitrawalia/Calcify#5]
Must include logo and name of app

**Comment by SubhradeepSS** [comment]
@pavitrawalia Would like to work on it.

**Comment by pavitrawalia** [comment]
You can work on this issue after the issue #4 is resolved

**Comment by utpalendubarman** [comment]
I want to contribute

**Comment by pavitrawalia** [comment]
@utpalendubarman You can work on this issue after the issue #4 is resolved

**Comment by pavitrawalia** [comment]
@utpalendubarman go ahead

**Comment by pavitrawalia** [comment]
Issue resolved
