### ISSUE TITLE
Activities get messed up in Landscape Mode

### ISSUE THREAD

**Issue by parjanyaacoder** [pavitrawalia/Calcify#63]
Bug-In Landscape mode the contents of various activities get messed up.Also the result of the calculation is gone in landscape mode.
Soln - Restricting the orientation of the app to portrait mode.

I would like to work on this issue.

**Comment by parjanyaacoder** [comment]
I would like to work on this issue

**Comment by pavitrawalia** [comment]
@parjanyaacoder go ahead

**Comment by pavitrawalia** [comment]
Issue resolved
