### ISSUE TITLE
Updating the navigation drawer header

### ISSUE THREAD

**Issue by pavitrawalia** [pavitrawalia/Calcify#65]
Tasks to be done 
1. Replace Android Studio by "Calcify"
2. Replace android.studio@android.com with info.calcify@gmail.com
3. Change default background colour of header to the background colour of logo

![20200209_083933](https://user-images.githubusercontent.com/30498337/74095542-6ab88f80-4b18-11ea-8f70-bee5c1e35c5e.jpg)

**Comment by utpalendubarman** [comment]
I want to contribute

**Comment by pavitrawalia** [comment]
@utpalendubarman go ahead

**Comment by pavitrawalia** [comment]
Issue resolved
