### ISSUE TITLE
Improvements in VAT and GST Activity

### ISSUE THREAD

**Issue by pavitrawalia** [pavitrawalia/Calcify#67]
Tasks to be done
1. Length of edit text views of Amount and rate must be identical
2. Width of "add" and "remove" button must be same.
3. Text in remove button must be in a single line.

![Screenshot_20200209-084823_Calcify](https://user-images.githubusercontent.com/30498337/74095597-4315f700-4b19-11ea-8688-04a94bb26ad7.jpg)

**Comment by utpalendubarman** [comment]
Hi, I like to contribute

**Comment by pavitrawalia** [comment]
@utpalendubarman go ahead

**Comment by pavitrawalia** [comment]
Issue resolved
