### ISSUE TITLE
Ui improvements in Unit conversion activity

### ISSUE THREAD

**Issue by pavitrawalia** [pavitrawalia/Calcify#68]
Tasks to be done
1. Change background colour to black.
2. Change colour of swap button to purple.

![Screenshot_20200209-085406_Calcify](https://user-images.githubusercontent.com/30498337/74095648-dea76780-4b19-11ea-8157-89a99b2d77c8.jpg)

**Comment by utpalendubarman** [comment]
I want to contribute

**Comment by pavitrawalia** [comment]
@utpalendubarman go ahead

**Comment by pavitrawalia** [comment]
issue resolved
